[project]
name = 'Quantum-Art-Gallery'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.experience-integration]
path = 'contracts/experience-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.quantum-art-management]
path = 'contracts/quantum-art-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
